import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <div style={{
          position: 'fixed',
          bottom: '14px',
          right: '16px',
          display: 'flex',
          alignItems: 'center',
          gap: '6px',
          opacity: 0.5,
        }}>
          <span style={{ fontSize: '13px', color: '#F0E6D3', letterSpacing: '0.02em' }}>Made by</span>
          <Image src="/nadak-logo.png" alt="nadak" height={26} width={90} style={{ filter: 'invert(1) brightness(2)', objectFit: 'contain' }} />
        </div>
      </body>
    </html>
  );
}
